// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { add } from "./add.js";
import { ceil } from "./ceil.js";
import { clamp } from "./clamp.js";
import { create } from "./create.js";
import { div } from "./div.js";
import { exp } from "./exp.js";
import { floor } from "./floor.js";
import { gt } from "./gt.js";
import { gte } from "./gte.js";
import { is } from "./is.js";
import { isBigInt } from "./isBigInt.js";
import { isFinite } from "./isFinite.js";
import { isFloat } from "./isFloat.js";
import { isInRange } from "./isInRange.js";
import { isInt } from "./isInt.js";
import { isNotFinite } from "./isNotFinite.js";
import { limitPrecision } from "./limitPrecision.js";
import { lt } from "./lt.js";
import { lte } from "./lte.js";
import { max } from "./max.js";
import { min } from "./min.js";
import { mul } from "./mul.js";
import { or } from "./or.js";
import { orElse } from "./orElse.js";
import { orThrow } from "./orThrow.js";
import { randomInt } from "./randomInt.js";
import { round } from "./round.js";
import { sub } from "./sub.js";
import { toFixed } from "./toFixed.js";
import { toString } from "./toString.js";

export const Number = {
    add,
    ceil,
    clamp,
    create,
    div,
    exp,
    floor,
    gt,
    gte,
    is,
    isBigInt,
    isFinite,
    isFloat,
    isInRange,
    isInt,
    isNotFinite,
    limitPrecision,
    lt,
    lte,
    max,
    min,
    mul,
    or,
    orElse,
    orThrow,
    randomInt,
    round,
    sub,
    toFixed,
    toString,
}
